# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1349, 835)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hauptFensterTeiler = QtWidgets.QWidget(MainWindow)
        self.hauptFensterTeiler.setMinimumSize(QtCore.QSize(850, 835))
        self.hauptFensterTeiler.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hauptFensterTeiler.setObjectName("hauptFensterTeiler")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hauptFensterTeiler)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollAusgabe = QtWidgets.QScrollArea(self.hauptFensterTeiler)
        self.scrollAusgabe.setEnabled(False)
        self.scrollAusgabe.setMinimumSize(QtCore.QSize(825, 0))
        self.scrollAusgabe.setLineWidth(0)
        self.scrollAusgabe.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAusgabe.setWidgetResizable(True)
        self.scrollAusgabe.setObjectName("scrollAusgabe")
        self.listeScrollAusgabe = QtWidgets.QWidget()
        self.listeScrollAusgabe.setGeometry(QtCore.QRect(0, 0, 823, 815))
        self.listeScrollAusgabe.setObjectName("listeScrollAusgabe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.listeScrollAusgabe)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top = QtWidgets.QWidget(self.listeScrollAusgabe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setMinimumSize(QtCore.QSize(800, 225))
        self.top.setMaximumSize(QtCore.QSize(800, 225))
        self.top.setStyleSheet("background-image: url(:/Bild/img/top.png);")
        self.top.setObjectName("top")
        self.eingang_ip_button = QtWidgets.QPushButton(self.top)
        self.eingang_ip_button.setGeometry(QtCore.QRect(114, 110, 174, 59))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.eingang_ip_button.setPalette(palette)
        self.eingang_ip_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.eingang_ip_button.setAutoFillBackground(False)
        self.eingang_ip_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.eingang_ip_button.setObjectName("eingang_ip_button")
        self.klartext_button = QtWidgets.QPushButton(self.top)
        self.klartext_button.setGeometry(QtCore.QRect(131, 24, 141, 31))
        self.klartext_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.klartext_button.setObjectName("klartext_button")
        self.schlussel_k_button = QtWidgets.QPushButton(self.top)
        self.schlussel_k_button.setGeometry(QtCore.QRect(533, 23, 141, 31))
        self.schlussel_k_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.schlussel_k_button.setObjectName("schlussel_k_button")
        self.pc_1_button = QtWidgets.QPushButton(self.top)
        self.pc_1_button.setGeometry(QtCore.QRect(531, 110, 141, 31))
        self.pc_1_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.pc_1_button.setObjectName("pc_1_button")
        self.verticalLayout_2.addWidget(self.top)
        self.middle = QtWidgets.QWidget(self.listeScrollAusgabe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middle.sizePolicy().hasHeightForWidth())
        self.middle.setSizePolicy(sizePolicy)
        self.middle.setMinimumSize(QtCore.QSize(800, 201))
        self.middle.setMaximumSize(QtCore.QSize(800, 201))
        self.middle.setStyleSheet("background-image: url(:/Bild/img/middle.png);")
        self.middle.setObjectName("middle")
        self.links_button = QtWidgets.QPushButton(self.middle)
        self.links_button.setGeometry(QtCore.QRect(110, 0, 101, 31))
        self.links_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.links_button.setObjectName("links_button")
        self.rechts_button = QtWidgets.QPushButton(self.middle)
        self.rechts_button.setGeometry(QtCore.QRect(210, 0, 101, 31))
        self.rechts_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.rechts_button.setObjectName("rechts_button")
        self.transformer_button = QtWidgets.QPushButton(self.middle)
        self.transformer_button.setGeometry(QtCore.QRect(533, 27, 141, 61))
        self.transformer_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.transformer_button.setObjectName("transformer_button")
        self.f_funktion_button = QtWidgets.QPushButton(self.middle)
        self.f_funktion_button.setGeometry(QtCore.QRect(200, 72, 31, 31))
        self.f_funktion_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.f_funktion_button.setObjectName("f_funktion_button")
        self.k_button = QtWidgets.QPushButton(self.middle)
        self.k_button.setGeometry(QtCore.QRect(380, 70, 41, 41))
        self.k_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.k_button.setObjectName("k_button")
        self.xor_button = QtWidgets.QPushButton(self.middle)
        self.xor_button.setGeometry(QtCore.QRect(129, 72, 31, 31))
        self.xor_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.xor_button.setObjectName("xor_button")
        self.verticalLayout_2.addWidget(self.middle)
        self.bottom = QtWidgets.QWidget(self.listeScrollAusgabe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom.sizePolicy().hasHeightForWidth())
        self.bottom.setSizePolicy(sizePolicy)
        self.bottom.setMinimumSize(QtCore.QSize(800, 295))
        self.bottom.setMaximumSize(QtCore.QSize(800, 295))
        self.bottom.setStyleSheet("background-image: url(:/Bild/img/bottom.png);")
        self.bottom.setObjectName("bottom")
        self.ausgang_ip_1_button = QtWidgets.QPushButton(self.bottom)
        self.ausgang_ip_1_button.setGeometry(QtCore.QRect(113, 115, 174, 60))
        self.ausgang_ip_1_button.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.ausgang_ip_1_button.setObjectName("ausgang_ip_1_button")
        self.links_button_letzer = QtWidgets.QPushButton(self.bottom)
        self.links_button_letzer.setGeometry(QtCore.QRect(100, 0, 101, 31))
        self.links_button_letzer.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.links_button_letzer.setObjectName("links_button_letzer")
        self.rechts_button_letzer = QtWidgets.QPushButton(self.bottom)
        self.rechts_button_letzer.setGeometry(QtCore.QRect(200, 0, 101, 31))
        self.rechts_button_letzer.setStyleSheet("background-image: url(:/Bild/img/btnbg.png);background-color:#000000")
        self.rechts_button_letzer.setObjectName("rechts_button_letzer")
        self.verticalLayout_2.addWidget(self.bottom)
        self.scrollAusgabe.setWidget(self.listeScrollAusgabe)
        self.horizontalLayout.addWidget(self.scrollAusgabe)
        self.scrollEingabe = QtWidgets.QScrollArea(self.hauptFensterTeiler)
        self.scrollEingabe.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollEingabe.setWidgetResizable(True)
        self.scrollEingabe.setObjectName("scrollEingabe")
        self.listeScrollEingabe = QtWidgets.QWidget()
        self.listeScrollEingabe.setGeometry(QtCore.QRect(0, 0, 498, 815))
        self.listeScrollEingabe.setObjectName("listeScrollEingabe")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.listeScrollEingabe)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eingabeKontrolle = QtWidgets.QGroupBox(self.listeScrollEingabe)
        self.eingabeKontrolle.setMaximumSize(QtCore.QSize(16777215, 300))
        self.eingabeKontrolle.setObjectName("eingabeKontrolle")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.eingabeKontrolle)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_klartext = QtWidgets.QLabel(self.eingabeKontrolle)
        self.label_klartext.setObjectName("label_klartext")
        self.verticalLayout.addWidget(self.label_klartext)
        self.klartext_eingabe = QtWidgets.QPlainTextEdit(self.eingabeKontrolle)
        self.klartext_eingabe.setObjectName("klartext_eingabe")
        self.verticalLayout.addWidget(self.klartext_eingabe)
        self.label_schluessel = QtWidgets.QLabel(self.eingabeKontrolle)
        self.label_schluessel.setObjectName("label_schluessel")
        self.verticalLayout.addWidget(self.label_schluessel)
        self.schluessel_eingabe = QtWidgets.QPlainTextEdit(self.eingabeKontrolle)
        self.schluessel_eingabe.setObjectName("schluessel_eingabe")
        self.verticalLayout.addWidget(self.schluessel_eingabe)
        self.enterInput = QtWidgets.QPushButton(self.eingabeKontrolle)
        self.enterInput.setObjectName("enterInput")
        self.verticalLayout.addWidget(self.enterInput)
        self.verticalLayout_4.addWidget(self.eingabeKontrolle)
        self.informationKontroll = QtWidgets.QGroupBox(self.listeScrollEingabe)
        self.informationKontroll.setEnabled(False)
        self.informationKontroll.setObjectName("informationKontroll")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.informationKontroll)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addWidget(self.informationKontroll)
        self.scrollEingabe.setWidget(self.listeScrollEingabe)
        self.horizontalLayout.addWidget(self.scrollEingabe)
        MainWindow.setCentralWidget(self.hauptFensterTeiler)

        self.retranslateUi(MainWindow)
        self.enterInput.clicked.connect(MainWindow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.eingang_ip_button.setText(_translate("MainWindow", "Eingang IP"))
        self.klartext_button.setText(_translate("MainWindow", "Klartext x"))
        self.schlussel_k_button.setText(_translate("MainWindow", "Schlussel k"))
        self.pc_1_button.setText(_translate("MainWindow", "PC-1"))
        self.links_button.setText(_translate("MainWindow", "L #"))
        self.rechts_button.setText(_translate("MainWindow", "R #"))
        self.transformer_button.setText(_translate("MainWindow", "Transformater #"))
        self.f_funktion_button.setText(_translate("MainWindow", "f"))
        self.k_button.setText(_translate("MainWindow", "k #"))
        self.xor_button.setText(_translate("MainWindow", "XOR"))
        self.ausgang_ip_1_button.setText(_translate("MainWindow", "Ausgang IP_1"))
        self.links_button_letzer.setText(_translate("MainWindow", "L 16"))
        self.rechts_button_letzer.setText(_translate("MainWindow", "R 16"))
        self.eingabeKontrolle.setTitle(_translate("MainWindow", "Eingaben"))
        self.label_klartext.setText(_translate("MainWindow", "Klartext (64 Bit)"))
        self.label_schluessel.setText(_translate("MainWindow", "Schlüssel (64 Bit)"))
        self.enterInput.setText(_translate("MainWindow", "Verschlüsseln"))
        self.informationKontroll.setTitle(_translate("MainWindow", "Information"))

import Bilder_rc
